### ISSUE TITLE
No option to re-arange items in the list

### ISSUE THREAD

**Issue by cipricus** [Nomen-Luni/Bionic-Batch-Renamer#12]
This beats the purpose of having an option of numbering the files if the files cannot be ordered first. It is one of the Thunar tool's options but only partially implemented.

**Comment by cipricus** [comment]
> Hi, Sorry I've had a lot on my plate recently including the death of my father and my mother experiencing severe burns, on top of which QtCreator is for some reason broke on my current system.
> 
> I do want to get around to fixing things but there are higher priorities right now as I'm sure you'll appreciate.
> 
> Sounds like Thunar works better for you so I totally agree go for that.

I am very sorry to hear that! I wish, you and your loved ones, all the best!

**Comment by Nomen-Luni** [comment]
Thanks brother, that is appreciated. 
Once I do get around to it (whenever that is), I'll post back. Maybe there's still a chance to lure you from Thunar in the future. ;)

**Comment by Nomen-Luni** [comment]
I will have a look at what Thunar is doing and try to implement the same feature for the next release.

**Comment by cipricus** [comment]
> I will have a look at what Thunar is doing and try to implement the same feature for the next release.. coming soon.

Thank you for taking the time to answer. Amongst the 3 issues I've posted, this one is I guess the most important for operability (no meaningful way to use the numbering option without fixing this). The rest are not that severe, but I would surely like to see #11 fixed.

**Comment by Nomen-Luni** [comment]
Commented on #11 in that thread - state persistence will be in the next release.

**Comment by Nomen-Luni** [comment]
Code committed to drag and sort. Will be in next build.
