### ISSUE TITLE
Does not work if not all files have a pattern

### ISSUE THREAD

**Issue by almaceleste** [Nomen-Luni/Bionic-Batch-Renamer#4]
Really nice utility. 
But I have an issue.
If I select several files and want to replace some text, for example, `scene`, and some of these files have this text, but one does not, the utility does nothing. 
If I remove this file from the list of selected files - everything works fine. But such behavior, unfortunately, is very inconvenient.

**Comment by Nomen-Luni** [comment]
Thanks for the bug report. Behaviour confirmed and I think I know what
it is.

Fix incoming in the next week or two.

**Comment by Nomen-Luni** [comment]
Fixed in release 1.0.11 which you should receive through your package manager.
Thanks again almaceleste for the bug report and your positive review on KDE store. 😎👍
