### ISSUE TITLE
Please add a "fake tag" support, like TagSpaces

### ISSUE THREAD

**Issue by CavaleriOmar** [Nomen-Luni/Bionic-Batch-Renamer#7]
Would it be possible to implement tag support in the name as [TagSpaces](https://www.tagspaces.org/), perhaps with tag recognition?

TagSpaces is a remarkable app, but I am assiduously looking for a replacement because it is written in electron (and is painfully slow in use, even on an i5 with 16 gb of ram)

**Comment by Nomen-Luni** [comment]
Hi,
That looks like a cool app but I really don't think this functionality fits into my batch renamer, and very few people would be interested if it did. It's a better fit for a file manager so perhaps post it as a suggestion to the devs of your favourite one?
