### ISSUE TITLE
Menu icon absent in Kubuntu

### ISSUE THREAD

**Issue by cipricus** [Nomen-Luni/Bionic-Batch-Renamer#8]
I had to edit manually the desktop file and replace the `cm_multirename` icon, which was not recognized, with `edit-rename`.

**Comment by Nomen-Luni** [comment]
Hi Cipricus,

Sorry for the delay, I have some time now.

Kubuntu should really add the icon (it's a nice differentiation from the single rename icon with the set I use), but for the sake of compatibility I will change it to edit-rename as suggested.

This will be in the next build, coming soon.

**Comment by Nomen-Luni** [comment]
Code committed to use edit-rename icon. Will be in next build.
